### ISSUE TITLE
Remove dead apps

### ISSUE THREAD

**Issue by pirates-way** [SpamVerse/Piratezparty#55]
Remove dead apps from [Anime Apps](https://github.com/SpamVerse/Piratezparty/blob/main/Anime-Manga-Apps.md#android-anime)
Dead Apps - Anime Twist and AnimeBoya

I'm new to this, go easy and give me insights if I did something wrong.

**Comment by Piratezparty** [comment]
Done , in future you can even create pr directly, your previous pr was okay no idea why you closed but yeah you can create pr directly i will merge if i see everything okay there

**Comment by Piratezparty** [comment]
Done
