### ISSUE TITLE
typo in vpn link in readme

### ISSUE THREAD

**Issue by nyas1** [SpamVerse/Piratezparty#63]
https://github.com/SpamVerse/Piratezparty/blob/main/Privacy\VPN.md
should be https://github.com/SpamVerse/Piratezparty/blob/main/Privacy/VPN.md

**Comment by Piratezparty** [comment]
Create a pr

**Comment by Piratezparty** [comment]
Create a pull request

**Comment by Piratezparty** [comment]
Fixed , didn't read the issue carefully before.
